package com.sean.init.model;

import java.util.Date;

public class Lock {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock.lock_key
     *
     * @mbg.generated
     */
    private String lockKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock.desc
     *
     * @mbg.generated
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lock.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock.id
     *
     * @return the value of lock.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock.id
     *
     * @param id the value for lock.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock.lock_key
     *
     * @return the value of lock.lock_key
     *
     * @mbg.generated
     */
    public String getLockKey() {
        return lockKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock.lock_key
     *
     * @param lockKey the value for lock.lock_key
     *
     * @mbg.generated
     */
    public void setLockKey(String lockKey) {
        this.lockKey = lockKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock.desc
     *
     * @return the value of lock.desc
     *
     * @mbg.generated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock.desc
     *
     * @param desc the value for lock.desc
     *
     * @mbg.generated
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lock.update_time
     *
     * @return the value of lock.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lock.update_time
     *
     * @param updateTime the value for lock.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}