package com.sean.init.mapper;

import com.sean.init.model.Lock;
import com.sean.init.model.LockExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LockMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    long countByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int deleteByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int insert(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int insertSelective(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    List<Lock> selectByExample(LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    Lock selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Lock record, @Param("example") LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Lock record, @Param("example") LockExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Lock record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table lock
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Lock record);
}